src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date that this deadline needs to be finished by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>Deadline__c -  Kickoff__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Days between Kickoff and Deadline.</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>When should this milestone kickoff?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>The project this milestone is assigned to. If this is a sub-milestone this field is empty.</inlineHelpText>
        <label>Project</label>
        <referenceTo>Milestone1_Project__c</referenceTo>
        <relationshipLabel>Milestones</relationshipLabel>
        <relationshipName>Project_Milestones</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <formula>Hours_Budget__c + Hours_Budget_from_Sub_Milestones__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated as hours budget + hours budget from sub milestones</inlineHelpText>
        <label>Total Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Deadline__c</fullName>
        <inlineHelpText>The date by which the project is scheduled to be completed by.</inlineHelpText>
        <label>Deadline</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Duration__c</fullName>
        <formula>Deadline__c - Kickoff__c + 1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Number of days between Kickoff and Deadline.</inlineHelpText>
        <label>Duration</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>GoogleGanntUrl__c</fullName>
        <inlineHelpText>Calculated.</inlineHelpText>
        <label>GoogleGanntUrl</label>
        <length>32000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Kickoff__c</fullName>
        <inlineHelpText>What date should this project start?</inlineHelpText>
        <label>Kickoff</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Status_BudgetExpenseSummary__c</fullName>
        <formula>IF( Total_Expense_Budget__c &gt; 0,
IMAGE(
&quot;http://chart.apis.google.com/chart?chtt=Task+Expense+Budget+Analysis&amp;&quot; &amp;
&quot;chxr=0,0,&quot; &amp; Text(max( Total_Expense_Budget__c,Total_Expense_Budget_from_Milestones__c,Total_Expense_Estimate__c, Total_Expense_Incurred__c)) &amp; &quot;&amp;&quot; &amp;
&quot;chxt=y&amp;chbh=a&amp;chs=300x225&amp;cht=bvg&amp;&quot;&amp;
&quot;chco=2299bb,eeaa66,ee3322,666666&amp;&amp;&quot;&amp;
&quot;chdl=&quot;&amp;
&quot;Budget (&quot; &amp; TEXT(Total_Expense_Budget__c) &amp; &quot;)&quot;&amp;
&quot;|Planned (&quot; &amp; TEXT(Total_Expense_Budget_from_Milestones__c) &amp; &quot;)&quot;&amp;
&quot;|Estimated (&quot; &amp; TEXT(Total_Expense_Estimate__c) &amp; &quot;)&quot;&amp;
&quot;|Incurred (&quot; &amp; TEXT(Total_Expense_Incurred__c) &amp; &quot;)&quot;&amp;
&quot;&amp;chd=t:&quot;&amp;
TEXT( Total_Expense_Budget__c / max( Total_Expense_Budget__c,Total_Expense_Budget_from_Milestones__c,Total_Expense_Estimate__c, Total_Expense_Incurred__c) * 100 )&amp;&quot;|&quot;&amp; 
TEXT( Total_Expense_Budget_from_Milestones__c / max( Total_Expense_Budget__c,Total_Expense_Budget_from_Milestones__c,Total_Expense_Estimate__c, Total_Expense_Incurred__c) * 100)  &amp;&quot;|&quot; &amp; 
TEXT( Total_Expense_Estimate__c / max( Total_Expense_Budget__c,Total_Expense_Budget_from_Milestones__c,Total_Expense_Estimate__c, Total_Expense_Incurred__c) * 100 ) &amp;&quot;|&quot; &amp; 
TEXT(  Total_Expense_Incurred__c / max( Total_Expense_Budget__c,Total_Expense_Budget_from_Milestones__c,Total_Expense_Estimate__c, Total_Expense_Incurred__c) * 100) 
, &quot;Project Expense - Budget, Planned, Estimated, Incurred&quot;), &apos;&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Expense Summary - Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_BudgetMiletoneEstimate__c</fullName>
        <formula>&quot;http://chart.apis.google.com/chart?chtt=Task+Time+Budget+Analysis&amp;&quot;&amp;
&quot;chxr=0,0,&quot; &amp; Text(max( Total_Hours_Budget__c,Total_Hours_Budget_from_Milestones__c,Total_Hours_Estimate__c, Total_Hours_Incurred__c)) &amp; &quot;&amp;&quot; &amp;
&quot;chxt=y&amp;chbh=a&amp;chs=300x225&amp;cht=bvg&amp;&quot;&amp;
&quot;chco=2299bb,eeaa66,ee3322,666666&amp;&quot;&amp;
&quot;chdl=&quot;&amp;
&quot;Budget (&quot; &amp; TEXT(Total_Hours_Budget__c) &amp; &quot;)&quot;&amp;
&quot;|Planned (&quot; &amp; TEXT(Total_Hours_Budget_from_Milestones__c) &amp; &quot;)&quot;&amp;
&quot;|Estimated (&quot; &amp; TEXT(Total_Hours_Estimate__c) &amp; &quot;)&quot;&amp;
&quot;|Incurred (&quot; &amp; TEXT(Total_Hours_Incurred__c) &amp; &quot;)&quot;&amp;
&quot;&amp;chd=t:&quot;&amp;
TEXT( Total_Hours_Budget__c / max( Total_Hours_Budget__c,Total_Hours_Budget_from_Milestones__c,Total_Hours_Estimate__c, Total_Hours_Incurred__c) * 100 )&amp;&quot;|&quot;&amp; 
TEXT( Total_Hours_Budget_from_Milestones__c / max( Total_Hours_Budget__c,Total_Hours_Budget_from_Milestones__c,Total_Hours_Estimate__c, Total_Hours_Incurred__c) * 100)  &amp;&quot;|&quot; &amp; 
TEXT( Total_Hours_Estimate__c / max( Total_Hours_Budget__c,Total_Hours_Budget_from_Milestones__c,Total_Hours_Estimate__c, Total_Hours_Incurred__c) * 100 ) &amp;&quot;|&quot; &amp; 
TEXT(  Total_Hours_Incurred__c / max( Total_Hours_Budget__c,Total_Hours_Budget_from_Milestones__c,Total_Hours_Estimate__c, Total_Hours_Incurred__c) * 100)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Hours Summary - Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status_TasksOpenBlockedLate__c</fullName>
        <formula>IF(max(  Total_Open_Task_Count__c ,  Total_Late_Task_Count__c  , Total_Blocked_Task_Count__c ) &gt; 0 , 
&quot;http://chart.apis.google.com/chart?chtt=Open+Task+Analysis&amp;chxt=y&amp;chbh=a&amp;chs=300x225&amp;cht=bvg&amp;&quot;&amp;
&quot;chxr=0,0,&quot; &amp; Text(max(  Total_Open_Task_Count__c ,  Total_Late_Task_Count__c  , Total_Blocked_Task_Count__c ))&amp;&quot;&amp;&quot;&amp;
&quot;chco=2299bb,eeaa66,ee3322&amp;chdl=&quot;&amp;
&quot;Open (&quot; &amp; TEXT(Total_Open_Task_Count__c) &amp; &quot;)&quot;&amp;
&quot;|Late (&quot; &amp; TEXT(Total_Late_Task_Count__c) &amp; &quot;)&quot;&amp;
&quot;|Blocked (&quot; &amp; TEXT(Total_Blocked_Task_Count__c) &amp; &quot;)&quot;&amp;
&quot;&amp;chd=t:&quot;&amp; TEXT(Total_Open_Task_Count__c / max(  Total_Open_Task_Count__c ,  Total_Late_Task_Count__c  , Total_Blocked_Task_Count__c ) *100)&amp;&quot;|&quot;&amp; TEXT(Total_Late_Task_Count__c/ max(  Total_Open_Task_Count__c ,  Total_Late_Task_Count__c  , Total_Blocked_Task_Count__c ) *100) &amp;&quot;|&quot; &amp; TEXT(Total_Blocked_Task_Count__c/ max(  Total_Open_Task_Count__c ,  Total_Late_Task_Count__c  , Total_Blocked_Task_Count__c ) *100), &apos;/s.gif&apos;)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Open, Late &amp; Blocked Tasks - Deprecated</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Blocked_Task_Count__c</fullName>
        <inlineHelpText>How many tasks associated with this project are blocked? (Calculated)</inlineHelpText>
        <label>Total Blocked Task Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Complete_Task_Count__c</fullName>
        <inlineHelpText>How many complete tasks are there in this project?  (Calculated.)</inlineHelpText>
        <label>Total Complete Task Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <inlineHelpText>The total hours budget for this project.</inlineHelpText>
        <label>Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget_from_Milestones__c</fullName>
        <inlineHelpText>Calculated from hours budgets for milestones in this project.</inlineHelpText>
        <label>Total Hours Budget from Milestones</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Estimate__c</fullName>
        <inlineHelpText>Calculated from hours estimates on all child milestones</inlineHelpText>
        <label>Total Hours Estimate</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Incurred__c</fullName>
        <inlineHelpText>Calculated from time records related to tasks on all child milestones</inlineHelpText>
        <label>Total Hours Incurred</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Late_Task_Count__c</fullName>
        <inlineHelpText>How many tasks associated with this project are late?  (Calculated)</inlineHelpText>
        <label>Total Late Task Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Open_Task_Count__c</fullName>
        <inlineHelpText>How many open tasks are there in this project? (Calculated. Includes Late and Blocked tasks.)</inlineHelpText>
        <label>Total Open Task Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Task__c.object
<CustomObject>
    <description>Force.com Labs - PM - An activity that has hours, budget, and is assigned to a User.</description>
    <fields>
        <fullName>Project_Milestone__c</fullName>
        <inlineHelpText>The milestone that this task is assigned to.</inlineHelpText>
        <label>Milestone</label>
        <referenceTo>Milestone1_Milestone__c</referenceTo>
        <relationshipLabel>Tasks</relationshipLabel>
        <relationshipName>Project_Tasks</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Project__c</fullName>
        <formula>HYPERLINK(Project_Milestone__r.Project__c, Project_Milestone__r.Project__r.Name,&apos;_self&apos;)</formula>
        <inlineHelpText>A link to the Project which this task is included in via its milestone.</inlineHelpText>
        <label>Project</label>
        <type>Text</type>
    </fields>
    <label>Task</label>
    <nameField>
        <label>Project Task Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Tasks</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/Milestone1_Summary2.cls
/*
Copyright (c) 2011, salesforce.com, Inc.
All rights reserved.

Redistribution and use in source and binary forms, with or without modification,
are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice,
    this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice,
    this list of conditions and the following disclaimer in the documentation
    and/or other materials provided with the distribution.
    * Neither the name of the salesforce.com, Inc. nor the names of its contributors
    may be used to endorse or promote products derived from this software
    without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.
IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED
OF THE POSSIBILITY OF SUCH DAMAGE.

*/
public with sharing class Milestone1_Summary2 {

    private Map<String, Report> reportsByName;

    public ID targetProject {get; set;}
    public String searchText {get; set;}
    public List<Milestone1_Project__c> projectResults {get; private set;}
    public List<Milestone1_Milestone__c> milestoneResults {get; private set;}
    public List<Milestone1_Task__c> taskResults {get; private set;}
    public boolean displaySearchError {private get; private set;}
    public boolean searchLengthError {private get; private set;}
    public List<Pair> recentItems {get; private set;}
    public boolean hasSearchResultsError {
        get {
            return displaySearchError != null && displaySearchError == true;
        }
    }
    public boolean hasSearchLengthError {
    	get {
            return searchLengthError != null && searchLengthError == true;
    	}
    }
    public boolean hasProjectResults {
        get {
            return projectResults != null && !projectResults.isEmpty();
        }
    }
    public boolean hasMilestoneResults {
        get {
            return milestoneResults != null && !milestoneResults.isEmpty();
        }
    }
    public boolean hasTaskResults {
        get {
            return taskResults != null && !taskResults.isEmpty();
        }
    }
    public boolean hasSettings {
        get {
            return settings != null;
        }
    }
    public boolean isDeployed {
        get {
            Id myProfileId = UserInfo.getProfileId();
            Profile myProfile = [
                SELECT
                    Id,
                    Name
                FROM
                    Profile
                WHERE Id = :myProfileId
            ];
            Boolean objectsDeployed = true;

            if (myProfile.Name != 'System Administrator') {
                try {
                    Schema.DescribeFieldResult F = Schema.SObjectType.Milestone1_Milestone__C.fields.Name;
                    if (F.isAccessible() == true) {
                        return true;
                    } else {
                        return false;
                    }
                    return true;
                } catch (System.UnexpectedException e) {
                    return false;
                }
            }
            return objectsDeployed;
        }
    }

    public Milestone1_Settings__c settings = Milestone1_Settings__c.getInstance();

    public void initialize() {
        if (isDeployed) {
            loadRecentItems();
            loadReportsMap();
        }
    }

    private void loadRecentItems() {
        List<Milestone1_Project__c> recentProjects = [
            SELECT
                Id,
                Name
            FROM
                Milestone1_Project__c
            ORDER BY
                LastModifiedDate DESC
            LIMIT 5
        ];
        List<Milestone1_Milestone__c> recentMilestones = [
            SELECT
                Id,
                Name
            FROM
                Milestone1_Milestone__c
            ORDER BY
                LastModifiedDate DESC
            LIMIT 50
        ];
        List<Milestone1_Task__c> recentTasks = [
            SELECT
                Id,
                Name
            FROM
                Milestone1_Task__c
            ORDER BY
                LastModifiedDate DESC
            LIMIT 100
        ];

        this.recentItems = new List<Pair>();
        this.recentItems.addAll(createPairObjects(recentProjects, 'Project: '));
        this.recentItems.addAll(createPairObjects(recentMilestones, 'Milestone: '));
        this.recentItems.addAll(createPairObjects(recentTasks, 'Task: '));
    }

    private void loadReportsMap() {
        this.reportsByName = new Map<String, Report>();
        for (Report rep : [
            SELECT
                Id,
                Name,
                DeveloperName
            FROM
                Report
            WHERE
                Name LIKE '%(LPM1)'
        ]) {
            this.reportsByName.put(rep.DeveloperName, rep);
        }
    }

    public void searchProjects() {
        if (searchText.length() < 2) {
            this.searchLengthError = true;
            return;
        } else {
            this.searchLengthError = false;
        }

        List<List<SObject>> searchList = [
            FIND :searchText IN ALL FIELDS RETURNING
            Milestone1_Project__c (Id, Name, Owner.Name, Status__c LIMIT 5),
            Milestone1_Milestone__c (Id, Name, Project__r.Name LIMIT 10),
            Milestone1_Task__c (Id, Name, Project_Milestone__r.Name LIMIT 25)
        ];
        this.projectResults = (List<Milestone1_Project__c>)searchList[0];
        this.milestoneResults = (List<Milestone1_Milestone__c>)searchList[1];
        this.taskResults = (List<Milestone1_Task__c>)searchList[2];

        if (this.projectResults.isEmpty() && this.milestoneResults.isEmpty() && this.taskResults.isEmpty()) {
            this.displaySearchError = true;
        } else {
            this.displaySearchError = false;
        }
    }

    private List<Pair> createPairObjects(List<SObject> records, String namePrefix) {
        List<Pair> newPairs = new List<Pair>();
        for (SObject record: records) {
            //RSC 2011-05-06 am getting occassional script exceptions
            if (record != null && record.get('name') != null) {
                newPairs.add(new Pair(namePrefix + (String)record.get('name'), (String)record.id));
            }
        }
        return newPairs;
    }

    public List<Milestone1_Project__c> getProjects() {
         return (List<Milestone1_Project__c>) setCon.getRecords();
    }

    public ApexPages.StandardSetController setCon {
        get {
            if (setCon == null) {
                setCon = new ApexPages.StandardSetController(Database.getQueryLocator([
                    SELECT
                        Id,
                        Total_Open_Task_Count__c,
                        Total_Complete_Task_Count__c,
                        Total_Blocked_Task_Count__c,
                        Total_Late_Task_Count__c,
                        Status_TasksOpenBlockedLate__c,
                        Total_Hours_Budget__c,
                        Total_Hours_Budget_from_Milestones__c,
                        Total_Hours_Estimate__c,
                        Total_Hours_Incurred__c,
                        Status_BudgetMiletoneEstimate__c,
                        Status_BudgetExpenseSummary__c,
                        Name,
                        Deadline__c,
                        Kickoff__c,
                        Duration__c,
                        GoogleGanntUrl__c
                    FROM
                        Milestone1_Project__c
                    WHERE
                        Status__c = 'Active'
                ]));
                setCon.setPageSize(20);
            }
            return setCon;
        }
        set;
    }

    // Boolean to check if there are more records after the present displaying records
    public Boolean hasNext {
        get {
            return setCon.getHasNext();
        }
        set;
    }

    // Boolean to check if there are more records before the present displaying records
    public Boolean hasPrevious {
        get {
            return setCon.getHasPrevious();
        }
        set;
    }

    // Page number of the current displaying records
    public Integer pageNumber {
        get {
            return setCon.getPageNumber();
        }
        set;
    }

    public Integer totalPages {
        get {
            Integer pages = (setCon.getResultSize() / 20);
            if (math.mod(setCon.getResultSize(), 20) != 0) {
                pages += 1;
            }
            return pages;
        }
        set;
    }

    // Returns the previous page of records
    public void previous() {
        setCon.previous();
    }

    //Returns the next page of records
    public void next() {
        setCon.next();
    }

    public Pagereference view() {
        return new Pagereference('/' + targetProject);
    }

    public Pagereference viewMyTasks() {
        return new Pagereference(
            '/' + this.reportsByName.get('My_Project_Tasks') +
            '?pv0=' + String.valueOf(targetProject).substring(0,15) +
            '&pv1=' + UserInfo.getFirstName() + ' ' + UserInfo.getLastName()
        );
    }

    public Pagereference viewBlockedTasks() {
        return new Pagereference(
            '/' + this.reportsByName.get('Blocked_Tasks_by_Project') +
            '?pv0=' + String.valueOf(targetProject).substring(0,15)
        );
    }

    public Pagereference viewOverdueTasks() {
        return new Pagereference(
            '/' + this.reportsByName.get('Overdue_Tasks_by_Project') +
            '?pv0=' + String.valueOf(targetProject).substring(0,15)
        );
    }

    public Pagereference viewOpenTasks() {
        return new Pagereference(
            '/' + this.reportsByName.get('Open_Tasks_By_Project_LPM1') +
            '?pv0=' + String.valueOf(targetProject).substring(0,15)
        );
    }

    public Pagereference viewMilestoneOpenTasks() {
        return new Pagereference(
            '/' + this.reportsByName.get('Milestones_and_Open_Tasks_by_Proj_LPM1') +
            '?pv0=' + String.valueOf(targetProject).substring(0,15)
        );
    }

    public Pagereference incompleteTasksByProject() {
        return new Pagereference(
            '/' + this.reportsByName.get('My_Incomplete_Tasks_By_Project') +
            '?pv0=' + Encodingutil.urlEncode('' + UserInfo.getName(), 'UTF-8')
        );
    }

    public Pagereference incompleteTasksByPriority() {
        return new Pagereference(
            '/' + this.reportsByName.get('My_Incomplete_Tasks_By_Priority') +
            '?pv0=' + Encodingutil.urlEncode('' + UserInfo.getName(), 'UTF-8')
        );
    }

    public Pagereference summaryMyLateTasks() {
        return new Pagereference(
            '/' + this.reportsByName.get('Summary_My_Late_Tasks_LPM1') +
            '?pv0=' + Encodingutil.urlEncode('' + UserInfo.getName(), 'UTF-8')
        );
    }

    public Pagereference summaryMyBlockedTasks() {
        return new Pagereference(
            '/' + this.reportsByName.get('Summary_My_Blocked_Tasks_LPM1') +
            '?pv0=' + Encodingutil.urlEncode('' + UserInfo.getName(), 'UTF-8')
        );
    }

    class Pair {
        Pair(String key, String value) {
            this.key = key;
            this.value = value;
        }

        public String key {get; private set;}
        public String value {get; private set;}
    }
}