src/objects/Milestone1_Milestone__c.object
<CustomObject>
    <description>Force.com Labs - PM - Milestones are significant events in the life-cycle of a Project. Milestones can have tasks and sub-milestones associated with them.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the milestone.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Expense_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The expense budget for the milestone.</inlineHelpText>
        <label>Milestone Expense Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Hours_Budget__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>The hours budget for the milestone.</inlineHelpText>
        <label>Milestone Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <formula>Hours_Budget__c + Hours_Budget_from_Sub_Milestones__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <inlineHelpText>Calculated as hours budget + hours budget from sub milestones</inlineHelpText>
        <label>Total Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Milestone</label>
    <nameField>
        <label>Project Milestone Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Milestones</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Milestone1_Project__c.object
<CustomObject>
    <description>Force.com Labs - PM - A collaborative enterprise which has a planned goal. A project can have many milestones.</description>
    <fields>
        <fullName>Description__c</fullName>
        <inlineHelpText>A general description of the project.</inlineHelpText>
        <label>Description</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <inlineHelpText>The current status of the project.</inlineHelpText>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Planning</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>On Hold</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Total_Hours_Budget__c</fullName>
        <inlineHelpText>The total hours budget for this project.</inlineHelpText>
        <label>Hours Budget</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Milestone1_GettingStartedController_Test.cls
@IsTest
public with sharing class Milestone1_GettingStartedController_Test {

    static testMethod void testGetSettings() {
        Milestone1_GettingStartedController cont = new Milestone1_GettingStartedController();
        Milestone1_Settings__c settings = cont.getInitialSettingsWithoutSave();

        System.assert(!settings.Auto_Follow_Complete_Task__c);
        System.assert(!settings.Auto_Follow_Task__c);
        System.assert(!settings.Auto_Unfollow_Reassignment__c);
    }

    static testMethod void testGettingStartedProject() {
        String content = '<?xml version="1.0"?>' +
            '<export>' +
                '<meta>' +
                    '<exportPackage>Milestone1_Project_Export</exportPackage>' +
                    '<exportAuthor>Alejandro+De+Gregorio</exportAuthor>' +
                    '<exportOrganization>undefined</exportOrganization>' +
                    '<exportCreateDate>2014-11-12+20%3A21%3A40</exportCreateDate>' +
                    '<exportVersion>1.0</exportVersion>' +
                '</meta>' +
                '<Milestone1_Project__c>' +
                    '<Id>a05F000000NzLzpIAF</Id>' +
                    '<Total_Hours_Budget__c>10.00</Total_Hours_Budget__c>' +
                    '<Status__c>Planning</Status__c>' +
                    '<Description__c>Test+description.</Description__c>' +
                    '<Name>Test+project</Name>' +
                    '<Milestone1_Milestone__c>' +
                        '<Id>a03F000000Htu79IAB</Id>' +
                        '<Expense_Budget__c>0.00</Expense_Budget__c>' +
                        '<Hours_Budget__c>0.00</Hours_Budget__c>' +
                        '<Name>Test+milestone</Name>' +
                    '</Milestone1_Milestone__c>' +
                '</Milestone1_Project__c>' +
            '</export>';

        Document doc = new Document(
            Name = 'Starter Project (LPM1)',
            DeveloperName = 'Starter_Project_LPM1a',
            Body = Blob.valueOf(content),
            ContentType = 'text/plain',
            Type = 'xml',
            FolderId = UserInfo.getUserId()
        );
        insert doc;

        Test.startTest();
        Milestone1_GettingStartedController cont = new Milestone1_GettingStartedController();
        Milestone1_Project__c project = cont.handleGettingStartedProjectInitialization();
        System.assert(project != null);
        Test.stopTest();
    }
}